# Generated by Django 3.1.1 on 2022-11-18 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shaggydogtale', '0002_contribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contribution',
            old_name='part',
            new_name='section',
        ),
    ]
